# .prettierrc.yml

# Specify the file types to format
overrides:
  - files: "*.rb"
    options:
      parser: "ruby"
  - files: "*.yml"
    options:
      parser: "yaml"
      singleQuote: true
      trailingComma: "all"
  - files: "*.html.erb"
    options:
      parser: "html"
      singleQuote: true

# Global options
printWidth: 120
tabWidth: 2
singleQuote: true
trailingComma: "none"
